### ISSUE TITLE
fft_gtgram: number of frames different from MATLAB implementation for the same signal

### ISSUE THREAD

**Issue by jfsantos** [detly/gammatone#5]
While testing this for a real signal, I have noticed that the Python implementation of `fft_gtgram` results have less frames than the MATLAB implementation. A test script as well as .mat files containing the input audio and output from MATLAB can be found [here](https://gist.github.com/jfsantos/82de18a9c87b6d3d942a).

**Comment by detly** [comment]
I am very reluctant to *commit* to MATLAB syntax compatibility simply because I don't have MATLAB at home. In order to verify compatibility whenever I make changes, I'd need to wait around for someone else to check it.

I'd be happy to take in non-breaking changes that allow for MATLAB compatibility, as long as it's understood not to be a commitment to future MATLAB compatibility.

Regarding the version of `specgram` in `auditory_toolbox`: it's there because the behaviour of MATLAB's `specgram` has changed over the years, and the toolkit code (which was written against an older version) doesn't work for certain input dimensions or arguments with the new version.

**Comment by jfsantos** [comment]
I understand and agree completely. I'll try to get the same code working both on MATLAB and Octave, and will submit a pull request if I get something decent.
